### ISSUE TITLE
`data` is always empty

### ISSUE THREAD

**Issue by tombh** [PRosenb/AdbClipboard#1]
Does this look right for output?
```
Broadcasting: Intent { flg=0x400000 cmp=ch.pete.adbclipboard/.ReadReceiver }
Broadcast completed: result=2, data=""
```

**Comment by PRosenb** [comment]
Hi @tombh, thanks for your feedback. Are you using Android 10? I added a hint to the [main page](https://github.com/PRosenb/AdbClipboard/) that `AdbCliboard` is not compatible with it unfortunately.

**Comment by tombh** [comment]
Ah yes I'm on Android 10 :( Thank you though!  Do you have any other suggestions for getting the clipboard contents from my phone to my laptop?

**Comment by PRosenb** [comment]
It seams to still be an open issue at this stage..
https://www.androidpolice.com/2019/09/04/dont-upgrade-to-android-10-if-you-rely-on-clipboard-syncing/

**Comment by tombh** [comment]
Thanks for the info @PRosenb!

**Comment by TonyStark** [comment]
Actually it works on android 10, just copy text and keep `adbclipboard` app screen open.
Then you can retrieve clipboard in adb.
the thing is app is not working while its minimized

**Comment by PRosenb** [comment]
Yes that's right. Quite cumbersome unfortunately..

**Comment by GHolk** [comment]
Hey, I faced a similar problem. When my device's screen ls locked, I always get empty data response.

```term
~ $ # android's screen is locked
~ $ adb shell am broadcast -n ch.pete.adbclipboard/.ReadReceiver
Broadcasting: Intent { flg=0x400000 cmp=ch.pete.adbclipboard/.ReadReceiver }
Broadcast completed: result=2, data=""
~ $ # now android's screen is on
~ $ adb shell am broadcast -n ch.pete.adbclipboard/.ReadReceiver
Broadcasting: Intent { flg=0x400000 cmp=ch.pete.adbclipboard/.ReadReceiver }
Broadcast completed: result=-1, data="foo bar"
```
