### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [PRosenb/AdbClipboard#2]
Hi @PRosenb 

Since this app is Apache V2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, and it could be useful for some of us.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by PRosenb** [comment]
Hi @Poussinou , this app does not work on newer Android versions. It's therefore not worth it to port it to F-Droid.
Cheers

**Comment by Poussinou** [comment]
I though it would be interesting for people with a lower version of Android... But that's ok, thanks for your answer

**Comment by PRosenb** [comment]
Hi @Poussinou , I don't mind if someone else likes to do it 👍 , cheers

**Comment by PRosenb** [comment]
@Korb It works now with the described limitations, see [Using adb cmd to access clipboard on Android 10](https://github.com/PRosenb/AdbClipboard/issues/4#issuecomment-3148719239) or [Readme](https://github.com/PRosenb/AdbClipboard/).
