### ISSUE TITLE
Option to output unicode

### ISSUE THREAD

**Issue by Phaen** [PRosenb/AdbClipboard#5]
Both this app and Clipper run into the same issue where the ADB result cuts off at the first non-ASCII character. I would love an option to output something like a comma separated list of unicode values instead.

**Comment by PRosenb** [comment]
Hi @Phaen, thanks for your report. Given AdbClipboard cannot support newer Android versions, I don't extend it any more. I'm happy to review and merge a pull request if you like to implement the change yourself.
